TODO LIST

-SEARCH ABOUT ADMIN AND USER LOGIN
-PLANIFICACION: ESPEFICACION DE LOS OBJETIVOS Y METAS
-SEARCH ABOUT USERS ADMIN DASHBOARD
-HOW TO INTEGRADE APPS LINK TO THE DASHBOARD FOR USERS AND ADMIN
-STUDY PREVIOUS CODE (NOT IMPORTANT)